window.DATOS_POSICIONES = {
    // --- NIVEL FÁCIL (Tu lista completa) ---
    facil: [
        { nombre: "Encantador de serpientes", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_47.png" },
        { nombre: "Chibi", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_33.png" },
        { nombre: "Fuente", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_36.png" },
        { nombre: "Lamiendo al maestro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_44.png" },
        { nombre: "El hombre de las damas", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_70.png" },
        { nombre: "Adoración", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_18.png" },
        { nombre: "Lugar cómodo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_27.png" },
        { nombre: "Pony salvaje", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_17.png" },
        { nombre: "Vaquera en la silla", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_3.png" },
        { nombre: "Titanic", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/2_41_4.png" },
        { nombre: "Gemido", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_18.png" },
        { nombre: "Guardián", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_25.png" },
        { nombre: "Riverside", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_19.png" },
        { nombre: "Amateur", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_18.png" },
        { nombre: "Respiración cerrada", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_4.png" },
        { nombre: "Sucia sanchez", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_16.png" },
        { nombre: "Hambre", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_16.png" },
        { nombre: "Tornillo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_15.png" },
        { nombre: "Deseo asqueroso", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_69.png" },
        { nombre: "Beso francés", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_12.png" },
        { nombre: "Compliment", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_37.png" },
        { nombre: "Apetito", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_14.png" },
        { nombre: "Fusión", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_6.png" },
        { nombre: "Bonita charla", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_6.png" },
        { nombre: "Sala de espera", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_59.png" },
        { nombre: "Perrito en el borde", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_28.png" },
        { nombre: "Hélice", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_8.png" },
        { nombre: "Toque sensual", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_7.png" },
        { nombre: "Princesa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_11.png" },
        { nombre: "Toro mecanico", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_4_4.png" },
        { nombre: "Mujer madura", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_1.png" },
        { nombre: "Japón", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_1.png" },
        { nombre: "Inseminador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_4.png" },
        { nombre: "Boca de incendios", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/12_20_3.png" },
        { nombre: "Zeus", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/12_19.png" },
        { nombre: "Guardia de la Prisión", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/7_26_3.png" },
        { nombre: "Tauro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/7_25.png" },
        { nombre: "Juramento", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/7_24.png" },
        { nombre: "Colgante", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_15_4.png" },
        { nombre: "Leo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_24.png" },
        { nombre: "Valedictorio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_20_2.png" },
        { nombre: "Tabla de surf", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_23_3.png" },
        { nombre: "Arco", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_39_2.png" },
        { nombre: "Rana", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_28_2.png" },
        { nombre: "Entrenar", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_19_3.png" },
        { nombre: "Jockey", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_21_3.png" },
        { nombre: "Vaquera inversa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_41_3.png" },
        { nombre: "Prono", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_20_2.png" },
        { nombre: "Estilo perrito", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_23.png" },
        { nombre: "Llanura", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_18_2.png" },
        { nombre: "Vaquera", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_29.png" },
        { nombre: "Horizonte", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_9.png" },
        { nombre: "Regadera", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_27_2.png" },
        { nombre: "Brillante (69)", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/10_11_2.png" },
        { nombre: "Escorpio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/10_10.png" },
        { nombre: "Concha", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_10_2.png" },
        { nombre: "Misionero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_8.png" },
        { nombre: "Croissant", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_5_4.png" },
        { nombre: "Caída", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_6.png" },
        { nombre: "Bizet", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_3.png" },
        { nombre: "Soldado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_3.png" },
        { nombre: "Cleopatra", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_5.png" },
        { nombre: "Idilio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/10_3_2.png" },
        { nombre: "Armonía", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_5_3.png" },
        { nombre: "Esclavo sexual", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/12_2.png" },
        { nombre: "Libro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/10_2_2.png" },
        { nombre: "En Cuatro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/4_4_3.png" },
        { nombre: "Tulipán", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/1_5.png" },
        { nombre: "Cuchara", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/13_1.png" },
        { nombre: "Susurro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/12_1_3.png" },
        { nombre: "Inquisidor", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/11_1.png" },
        { nombre: "Barco", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/8_2.png" },
        { nombre: "Vela", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/7_1.png" },
        { nombre: "A horcajadas", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/6_1_2.png" },
        { nombre: "Gato", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/3_2_3.png" },
    ],

    // --- NIVEL MEDIO (Reserva) ---
    medio: [
        { nombre: "Caliente carl", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_82.png" },
        { nombre: "Descenso", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_26.png" },
        { nombre: "Catapult", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_43.png" },
        { nombre: "Stickman", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_31.png" },
        { nombre: "Juego emocionante", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_32.png" },
        { nombre: "Bolsa de té", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_38.png" },
        { nombre: "Minero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_42.png" },
        { nombre: "Inclinación", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_24.png" },
        { nombre: "Gimlet", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/07/18_13.png" },
        { nombre: "Relajación", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_15.png" },
        { nombre: "Cohete", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_25.png" },
        { nombre: "Caballero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_23.png" },
        { nombre: "Capucha", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/11_33_5.png" },
        { nombre: "Lucha", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_22.png" },
        { nombre: "Mirar al cielo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_26.png" },
        { nombre: "Jack", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_12.png" },
        { nombre: "Pincho", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_20.png" },
        { nombre: "Triángulo de las Bermudas", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_79.png" },
        { nombre: "Penetración orgásmica", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_19.png" },
        { nombre: "Plancha", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_21.png" },
        { nombre: "Volcado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/2_7_3.png" },
        { nombre: "Alfombra mágica", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_26.png" },
        { nombre: "Dulces coños", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_20.png" },
        { nombre: "Bung", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_9.png" },
        { nombre: "Fuegos artificiales", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_5.png" },
        { nombre: "Car mecánico", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_18.png" },
        { nombre: "Atardecer español", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_21.png" },
        { nombre: "Línea recta", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/2_46.png" },
        { nombre: "Delicadeza", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_23.png" },
        { nombre: "Valedictorio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_17.png" },
        { nombre: "Pingüino", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_16.png" },
        { nombre: "Estilo mexicano", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_19.png" },
        { nombre: "Aventurero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_15.png" },
        { nombre: "Castigo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_19.png" },
        { nombre: "Vacaciones", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_24.png" },
        { nombre: "Oasis", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_72_3.png" },
        { nombre: "Inventivo 69", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_77.png" },
        { nombre: "Titanic - 2", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_27.png" },
        { nombre: "Dulce pecado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_71_1.png" },
        { nombre: "Nocturno", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_14.png" },
        { nombre: "Abismo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_9.png" },
        { nombre: "Vaquera sobre la mesa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_22.png" },
        { nombre: "Cartel erótico", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_16.png" },
        { nombre: "Mesa de café", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_60_2.png" },
        { nombre: "Necesidad de velocidad", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_8.png" },
        { nombre: "Piernas en el aire", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_20.png" },
        { nombre: "Arte chino", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_14.png" },
        { nombre: "Deslizamiento", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_36.png" },
        { nombre: "Respaldo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_18.png" },
        { nombre: "Conquistador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_7.png" },
        { nombre: "Cuña", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_21.png" },
        { nombre: "Hada", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_17.png" },
        { nombre: "Increíble encuentro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_9.png" },
        { nombre: "Multiplicar el placer", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_15.png" },
        { nombre: "Chocolate con leche", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_14.png" },
        { nombre: "Carrera descendente", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_6.png" },
        { nombre: "Cortesana", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_2.png" },
        { nombre: "Trabajador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_2.png" },
        { nombre: "Pterodáctilo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_4.png" },
        { nombre: "Chica tímida", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_5.png" },
        { nombre: "Noche de pereza", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_4.png" },
        { nombre: "XXX", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_10.png" },
        { nombre: "Luz de luna", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_41_1.png" },
        { nombre: "Tulipán", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_63.png" },
        { nombre: "Guitarra española", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_7.png" },
        { nombre: "Pastel en el cielo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/11_22_6.png" },
        { nombre: "Recarga", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_5.png" },
        { nombre: "Silencio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_6.png" },
        { nombre: "Garganta profunda", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_87.png" },
        { nombre: "Chili dog", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_23_2.png" },
        { nombre: "Tentación", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_3.png" },
        { nombre: "Horno holandés", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_4.png" },
        { nombre: "Tira y afloja", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_8.png" },
        { nombre: "Silla blanda", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_2.png" },
        { nombre: "Louise", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_63.png" },
        { nombre: "Titular", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_12.png" },
        { nombre: "Tumbona", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/3_22_3.png" },
        { nombre: "Baile lento", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_21.png" },
        { nombre: "Zodiaco", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_11.png" },
        { nombre: "Camión", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_2.png" },
        { nombre: "Canadian", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_23_3.png" },
        { nombre: "Cobra", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_68.png" },
        { nombre: "Cosmo tántrico", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/3_72_4.png" },
        { nombre: "Contraalmirante", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_17_4.png" },
        { nombre: "Perrito bajo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/8_29_4.png" },
        { nombre: "Puñetazo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_10.png" },
        { nombre: "Chef", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_2.png" },
        { nombre: "Cóctel jamaicano", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_7_4.png" },
        { nombre: "Saltamontes", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_22.png" },
        { nombre: "Isla del desierto", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_33.png" },
        { nombre: "Inicio bajo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_28_3.png" },
        { nombre: "Vaquera doblada", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_52.png" },
        { nombre: "Pokemon", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_3.png" },
        { nombre: "Plataforma de lanzamiento íntima", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/5_15_4.png" },
        { nombre: "Fontanero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_48.png" },
        { nombre: "Desvergonzado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/2_41_5.png" },
        { nombre: "Hisopo de la garganta", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_9.png" },
        { nombre: "El amante más sexy", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/15_15.png" },
        { nombre: "Entrada secreta", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_9.png" },
        { nombre: "Lagartija", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_11_1.png" },
        { nombre: "Cueva", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/4_34_3.png" },
        { nombre: "Rock and roll", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_47.png" },
        { nombre: "Carrera de espaldas", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/3_21.png" },
        { nombre: "Deleite", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/17_16.png" },
        { nombre: "Plato picante", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/19_10.png" },
        { nombre: "La bella durmiente", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/8_23_4.png" },
        { nombre: "Rehén", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_20.png" },
        { nombre: "Aterrizaje suave", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/16_1.png" },
        { nombre: "Ladyboy", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/1_9.png" },
        { nombre: "Joven semental", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/18_3.png" },
        { nombre: "Maestro", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2019/06/14_13.png" },
        { nombre: "Géminis", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/1_72_2.png" },
        { nombre: "Salto", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/7_32_2.png" },
        { nombre: "Spork", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/13_29_3.png" },
        { nombre: "Perro hacia abajo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/8_29_3.png" },
        { nombre: "Torre Eiffel", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/7_30_2.png" },
        { nombre: "Spiderman", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/4_37_4.png" },
        { nombre: "Helicóptero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/8_28_4.png" },
        { nombre: "Bicicleta", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/7_28_2.png" },
        { nombre: "Cuna", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/1_61.png" },
        { nombre: "Unicornio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/13_27_3.png" },
        { nombre: "Emperador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/8_27.png" },
        { nombre: "Capitán", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/5_45_3.png" },
        { nombre: "Rompecabezas", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/1_57.png" },
        { nombre: "Plaza T", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/13_26_2.png" },
        { nombre: "Nirvana", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/5_43_3.png" },
        { nombre: "Leopardo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/4_34_2.png" },
        { nombre: "Fontanero", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/04/12_16.png" },
        { nombre: "Héroe", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_41_3.png" },
        { nombre: "Helado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_32_2.png" },
        { nombre: "Vaquera al revés", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_50_3.png" },
        { nombre: "Domador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_24_4.png" },
        { nombre: "Esfinge", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_21_3.png" },
        { nombre: "Arpa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_40_2.png" },
        { nombre: "Aries", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_49_2.png" },
        { nombre: "Águila", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_37_2.png" },
        { nombre: "Trineo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_48.png" },
        { nombre: "Amazonas", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_51_4.png" },
        { nombre: "Gemelos", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/9_21.png" },
        { nombre: "Twix", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_33.png" },
        { nombre: "Batman", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_12.png" },
        { nombre: "Emmanuel", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_18.png" },
        { nombre: "Arco Iris", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_28_2.png" },
        { nombre: "Estrella de mar", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_44_4.png" },
        { nombre: "Sed", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_19_2.png" },
        { nombre: "Mujer prisionera", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_11_3.png" },
        { nombre: "Diosa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_17_2.png" },
        { nombre: "Baile erótico", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_22.png" },
        { nombre: "Acróbata", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_26.png" },
        { nombre: "Candelabro Italiano", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_24.png" },
        { nombre: "Callejón", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_37_3.png" },
        { nombre: "Clip", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_17_2.png" },
        { nombre: "Espejismo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_10_2.png" },
        { nombre: "Borrador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_15.png" },
        { nombre: "Pretzel", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_24_4.png" },
        { nombre: "Yunque", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_22_2.png" },
        { nombre: "Silla", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_21_2.png" },
        { nombre: "Tiramisú", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_14_2.png" },
        { nombre: "Flash", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_19_2.png" },
        { nombre: "Cuchilla", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_8_3.png" },
        { nombre: "Caracol", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_13_3.png" },
        { nombre: "Flatiron", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_13.png" },
        { nombre: "Diamante", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_21_4.png" },
        { nombre: "Iris", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_16_3.png" },
        { nombre: "Dejavu", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_25_3.png" },
        { nombre: "Descarga", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_7_2.png" },
        { nombre: "Fruta Prohibida", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_11.png" },
        { nombre: "Venus", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/7_11_2.png" },
        { nombre: "Cerradura", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_19_3.png" },
        { nombre: "Rodeo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_10_2.png" },
        { nombre: "Cangrejo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_22_2.png" },
        { nombre: "Mariposa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_10.png" },
        { nombre: "Sinfonía", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_6_2.png" },
        { nombre: "Yin-Yang", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/10_9_2.png" },
        { nombre: "Perro perezoso", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_10_4.png" },
        { nombre: "Bud", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_17.png" },
        { nombre: "Bulldog", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_13_2.png" },
        { nombre: "Rosa", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_11_2.png" },
        { nombre: "Caso", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_19_3.png" },
        { nombre: "Mástil", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/11_9_3.png" },
        { nombre: "Orador", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/10_7.png" },
        { nombre: "Cangrejo (Dorsal)", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_9.png" },
        { nombre: "Pendiente", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/5_15_2.png" },
        { nombre: "Tortuga", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_11.png" },
        { nombre: "Águila de la Mancha", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/3_7_3.png" },
        { nombre: "Tiara", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_10_3.png" },
        { nombre: "Precipicio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_18_2.png" },
        { nombre: "Creme brulee", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_6_2.png" },
        { nombre: "Malvavisco", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/12_4_2.png" },
        { nombre: "Montaña mágica", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_7_2.png" },
        { nombre: "Afrodita", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/6_6.png" },
        { nombre: "Monja", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_9_3.png" },
        { nombre: "Tigre agazapado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_14_3.png" },
        { nombre: "Cáncer", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/8_6_2.png" },
        { nombre: "Gancho", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/7_4_3-1.png" },
        { nombre: "Éxtasis", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/6_5.png" },
        { nombre: "Excavaciones", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/4_5_2.png" },
        { nombre: "Ape", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/2_8.png" },
        { nombre: "Jinete", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_10_2.png" },
        { nombre: "Encuadernación", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/13_2_4.png" },
        { nombre: "Garganta", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/11_4.png" },
        { nombre: "Estilo indio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/9_2_2.png" },
        { nombre: "Gota de nieve", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/8_5_4.png" },
        { nombre: "Pared", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/7_3.png" },
        { nombre: "Sprout", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/6_4.png" },
        { nombre: "Tornado", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/3_4_3.png" },
        { nombre: "Columpio", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/2_7_2.png" },
        { nombre: "Círculo", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/10_1.png" },
        { nombre: "Disco", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/9_1_2.png" },
        { nombre: "Acuario", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/5_7.png" },
        { nombre: "Batiente", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/4_1_3.png" },
        { nombre: "Lanzadera", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/1_3_3.png" }
    ],

    // --- NIVEL DIFÍCIL (Reserva) ---
    dificil: [
        { nombre: "De Pie", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/02/7_1.png" },
        { nombre: "La Carretilla", img: "https://sexpositions.club/es/wp-content/uploads/sites/2/2016/03/1_29.png" }
    ]
};
