window.DATOS_VR = {
    // ============================================================
    // NIVEL 1: SUAVE (Romance, Ropa fuera y Primeros Juegos)
    // ============================================================
    suave: {
        verdad: [
            "¿Qué es lo primero que te fijaste en mí?",
            "¿Cuál es la parte de mi cuerpo que más te gusta?",
            "¿Qué ropa interior mía te pone más?",
            "¿Recuerdas dónde tuvimos nuestro mejor polvo?",
            "¿Qué es lo que hago que más te excita?",
            "¿Te gusta que te muerda suave o fuerte?",
            "¿Prefieres arriba o abajo?",
            "¿Qué canción te recuerda a cuando lo hacemos?",
            "¿Cuál es tu zona más sensible?",
            "¿Te has tocado pensando en mí hoy?",
            "¿Qué pensaste la primera vez que me viste desnudo/a?",
            "¿Te gustan los besos con lengua o piquitos?",
            "¿Cuál es tu fantasía romántica secreta?",
            "¿Te gustaría hacerlo frente a un espejo?",
            "¿Qué te gustaría que te hiciera ahora mismo?",
            "¿Te gusta que te hable sucio o prefieres silencio?",
            "¿Luces encendidas o apagadas?",
            "¿Mañanero o nocturno?",
            "¿Qué masaje te relaja más?",
            "¿Te gusta ver cómo me toco?",
            "Di tres cosas que te ponen cachondo/a de mí.",
            "¿Cuál fue el lugar más arriesgado donde nos besamos?",
            "¿Te gusta que te domine o dominar?",
            "¿Qué harías si te dejara hacer lo que quisieras por 1 hora?"
        ],
        reto: [
            // --- JUEGOS DE LA APP (ALTA PROBABILIDAD) ---
            "APP: Ve a la RULETA, tira en 'Suave' y cumple lo que salga.",
            "APP: Ve a la RULETA, tira en 'Suave' y cumple lo que salga.",
            "APP: Ve a la RULETA, tira en 'Suave' y cumple lo que salga.", 
            "APP: Ve a POSICIONES (Fácil), busca una que te guste y dímela al oído.",
            "APP: Ve a POSICIONES (Fácil) e imitad esa postura con ropa ahora mismo.",
            "APP: Tira la RULETA. Si sale 'Besar', te quitas una prenda.",
            "APP: Ve a la RULETA. Tienes que cumplir la acción durante 1 minuto.",
            
            // --- ROPA FUERA (ALTA PROBABILIDAD) ---
            "¡QUÍTATE UNA PRENDA! (Sin rechistar).",
            "¡QUÍTATE UNA PRENDA! (Sin rechistar).",
            "¡QUÍTATE UNA PRENDA! (La que yo elija).", 
            "ELIGE: Ve a la RULETA y cumple O quítate una prenda.",
            "ELIGE: Bésame el cuello 1 min O quítate una prenda.",
            "¡QUÍTATE LOS ZAPATOS O CALCETINES!",
            
            // --- META-RETOS (DINÁMICA DE JUEGO) ---
            "JUEGO: En tu próximo turno estás OBLIGADO/A a elegir RETO.",
            "JUEGO: Juega otra vez inmediatamente. Elige Verdad o Reto ahora.",

            // --- RETOS NORMALES ---
            "Dame un beso de película durante 1 minuto.",
            "Hazme un masaje en los hombros durante 2 minutos.",
            "Bésame el cuello suavemente sin dejar marca.",
            "Pásame un hielo por el cuello y el pecho.",
            "Susúrrame al oído lo que me harás más tarde.",
            "Quítame una prenda de ropa usando solo los dientes.",
            "Muerde suavemente el lóbulo de mi oreja.",
            "Bésame recorriendo toda mi espalda.",
            "Déjame escribirte una palabra en el cuerpo con la lengua.",
            "Acaricia mis muslos interiores sin tocar el centro.",
            "Dame 10 besos rápidos donde tú quieras.",
            "Desabróchame el pantalón pero no lo bajes.",
            "Hazme cosquillas suaves en el abdomen.",
            "Mírame a los ojos fijamente mientras te tocas los labios.",
            "Bésame el ombligo.",
            "Pon mi mano dentro de tu ropa interior por 30 segundos.",
            "Baila pegado a mí una canción lenta.",
            "Véndame los ojos y dame un beso sorpresa.",
            "Hazme un masaje de pies.",
            "Juega con mi pelo mientras me besas.",
            "Lame mi cuello de abajo a arriba.",
            "Pon tu mano en mi paquete/entrepierna y déjala ahí 1 minuto.",
            "Si llevas sujetador, desabróchalo (si no, quítate algo más).",
            "Haz que se me ponga la piel de gallina solo respirando en mi nuca.",
            "Dame un beso con sabor (come o bebe algo antes).",
            "Acaricia mi pecho por encima de la ropa.",
            "Dime un piropo muy guarro al oído.",
            "Siéntate en mis rodillas y bésame.",
            "Chupa mi dedo pulgar mirándome a los ojos.",
            "Hazme un chupetón en un lugar no visible.",
            "Pasa tus dedos por mis labios.",
            "Sopla suavemente en mi oreja.",
            "Desnuda mi torso (o quítame la camiseta).",
            "Tócate los pezones por encima de la ropa mirándome.",
            "Acaríciame el trasero con las dos manos.",
            "Bésame la parte interior de la muñeca.",
            "Muerde mi labio inferior suavemente.",
            "Pasa tu nariz por mi cuello y huele mi perfume/olor.",
            "Dime 'te deseo' con tu voz más sexy.",
            "Explora mi cuerpo con tus manos (sin tocar zonas íntimas) 1 min.",
            "Siéntate frente a mí y abre las piernas 5 segundos.",
            "Hazte una foto sexy y envíamela ahora mismo."
        ]
    },

    // ============================================================
    // NIVEL 2: HOT (Interacción total con la App y desnudos)
    // ============================================================
    hot: {
        verdad: [
            "¿Te has imaginado a algún amigo/a nuestro desnudo?",
            "¿Cuál es tu video porno favorito?",
            "¿Qué juguete sexual te gustaría probar?",
            "¿Alguna vez has fingido un orgasmo?",
            "¿Te gusta tragar o que te acabe en el cuerpo?",
            "¿Te pone cachondo/a verme vestirme o desvestirme?",
            "¿Qué lugar de la casa te excita más?",
            "¿Te gustaría que nos grabáramos?",
            "¿Qué opinas del sexo en la primera cita?",
            "¿Cuál es la postura que hace que te vengas más rápido?",
            "¿Te gusta que te tire del pelo?",
            "¿Has tenido sexo en un coche?",
            "¿Te gusta el sexo oral recíproco (69)?",
            "¿Qué es lo más sucio que has pensado hoy?",
            "¿Te gusta ver porno juntos?",
            "¿Qué ropa interior llevas ahora (descríbela)?",
            "¿Te gustaría usar esposas suaves?",
            "¿Prefieres hacerlo rápido o lento y tortuoso?",
            "¿Qué gemido mío te gusta más?",
            "¿Alguna vez te han pillado haciéndolo?",
            "¿Te gusta hacerlo con la regla?",
            "¿Cuál es tu lubricante o sabor favorito?",
            "¿Te gustaría hacer un trío (hipotéticamente)?",
            "¿Te pone cachondo/a el voyeurismo (mirar)?"
        ],
        reto: [
            // --- JUEGOS DE LA APP (MUY FRECUENTES) ---
            "APP: Ve a la RULETA (Picante) y haz EXACTAMENTE lo que diga.",
            "APP: Ve a la RULETA (Picante) y haz EXACTAMENTE lo que diga.", 
            "APP: Ve a la RULETA (Picante). Si sale tiempo > 30s, te quitas ropa.",
            "APP: Ve a POSICIONES (Medio). La primera que salga, la hacéis 2 min.",
            "APP: Ve a POSICIONES (Medio). La primera que salga, la hacéis 2 min.", 
            "APP: Ve a POSICIONES (Medio). Imitad la postura desnudos.",
            "APP: Tira la RULETA 3 veces y elige tu combinación favorita para hacérmela.",
            "APP: Ve a la RULETA (Mix). Si sale una zona íntima, ¡premio! Toca.",
            "APP: Ve a POSICIONES. Busca una que nunca hayamos hecho y probadla.",
            "APP: Tira la RULETA. Lo que salga se hace DOBLE de tiempo.",

            // --- ROPA FUERA Y ELECCIONES (ALTA FRECUENCIA) ---
            "¡QUÍTATE LA ROPA INTERIOR Y DÁMELA!",
            "¡QUÍTATE LA ROPA INTERIOR Y DÁMELA!",
            "¡QUÍTATE LA ROPA INTERIOR Y DÁMELA!", 
            "ELIGE: O me haces oral 1 min O te quitas la ropa interior.",
            "ELIGE: O tiras la RULETA (Picante) O te quitas dos prendas.",
            "ELIGE: O vamos a POSICIONES (Medio) O te quitas los pantalones.",
            "¡PRENDA FUERA! Tú eliges cuál, pero tiene que ser sexy.",
            "¡PRENDA FUERA! Tú eliges cuál, pero tiene que ser sexy.", 
            "ELIGE: O lames mis pezones O te quitas la camiseta.",
            "ELIGE: O me haces una paja/dedos O te quitas la ropa interior.",

            // --- META-RETOS ---
            "JUEGO: Haz DOS retos seguidos. Saca otra tarjeta de reto ahora mismo.",
            "JUEGO: Castigo. Quítate una prenda y tira la Ruleta Picante.",

            // --- RETOS NORMALES ---
            "Bésame desde el cuello hasta el ombligo.",
            "Tócame por encima de la ropa interior hasta que gima.",
            "Déjame tocarte donde yo quiera durante 1 minuto.",
            "Quítate toda la ropa de cintura para arriba.",
            "Hazme sexo oral superficial (sin meterla/chupar a fondo) 1 min.",
            "Mete la mano en mi ropa interior y mastúrbame 30 segundos.",
            "Ponte encima de mí y roza tus partes con las mías (con ropa).",
            "Lame mis pezones hasta ponerlos duros.",
            "Deja que te vende los ojos y adivina qué parte de mi cuerpo te toca.",
            "Quítate los pantalones/falda.",
            "Haz un striptease con una canción que yo elija.",
            "Usa un cubito de hielo para recorrer mi cuerpo desnudo.",
            "Bésame la cara interna de los muslos.",
            "Si eres chico: deja que te toque el paquete. Si eres chica: deja que te toque el pecho.",
            "Muerde mi cuello con intención de marcar.",
            "Susúrrame paso a paso cómo me follarías ahora.",
            "Bebe un trago de bebida del ombligo o pecho de tu pareja.",
            "Mastúrbate delante de mí durante 1 minuto.",
            "Déjame darte 3 nalgadas.",
            "Ponte a cuatro patas y deja que te admire.",
            "Haz 'Twerking' o mueve el culo en mi paquete 30 segundos.",
            "Intercambiamos una prenda de ropa.",
            "Chupa mi dedo simulando que es otra cosa.",
            "Déjame morderte el trasero.",
            "Siéntate en mi cara (con ropa) durante 10 segundos.",
            "Acaríciame el perineo (zona entre genitales y atrás) por encima de la ropa.",
            "Bésame apasionadamente usando mucha lengua.",
            "Hazme una paja (o dedeos) rápida de 1 minuto.",
            "Quítate toda la ropa excepto una prenda.",
            "Lame mi oreja y gime.",
            "Ponte un objeto frío (hielo/lata) en la entrepierna 10 segundos.",
            "Come una fruta de forma erótica mirándome.",
            "Pellizca mis pezones suavemente.",
            "Masajea mis nalgas con aceite o crema.",
            "Déjame besarte la espalda baja y el inicio del culo.",
            "Roza tu lengua por mis labios sin besarme.",
            "Hazme un baile erótico privado.",
            "Siéntate encima de mí mirándome y bésame.",
            "Tócate mientras te beso el cuello.",
            "Quítame la ropa interior sin usar las manos.",
            "Déjame ver tu historial de búsqueda del móvil.",
            "Simula un orgasmo ruidoso (Si no se puede hacer ruido: hazlo gesticulando en absoluto silencio).",
            "Bésame donde más te apetezca ahora mismo."
        ]
    },

    // ============================================================
    // NIVEL 3: DURO (Acción real + App obligatoria + Calentamiento)
    // ============================================================
    duro: {
        verdad: [
            "¿Te gustaría que te atara ahora mismo?",
            "¿Cuál es tu fantasía más sucia que no hemos hecho?",
            "¿Te gusta que te ahogue un poco?",
            "¿Has pensado en follar con alguien más estando conmigo?",
            "¿Te gustaría hacerlo en un sitio público ahora?",
            "¿Qué es lo más guarro que has hecho nunca?",
            "¿Te gusta que te escupan?",
            "¿Te gustaría usar un dildo o vibrador juntos?",
            "¿Cuál es la posición que más te estimula sin llegar al final?", 
            "¿Te gusta el sexo rudo o con amor?",
            "¿Te gustaría que te azotara fuerte?",
            "¿Has tenido sueños húmedos conmigo?",
            "¿Qué frase sucia te gustaría que te gritara al oído mientras te provoco?", 
            "¿Te excita el riesgo de que nos pillen?",
            "¿Te gustaría probar el sexo telefónico?",
            "¿Te pone ver porno de alguna categoría rara?",
            "¿Qué te gustaría que te obligara a hacer?",
            "¿Te gusta que te tapen la boca durante el sexo?",
            "¿Te gustaría que te vendara y usara juguetes contigo?",
            "¿Qué opinas del sexo durante la menstruación (real)?",
            "¿Te gustaría follar frente a una ventana abierta?"
        ],
        reto: [
            // --- JUEGOS DE LA APP (HARDCORE - FRECUENCIA ALTA) ---
            "APP: Ve a POSICIONES (Difícil). Tienes que hacer esa postura 5 MINUTOS.",
            "APP: Ve a POSICIONES (Difícil). Tienes que hacer esa postura 5 MINUTOS.", 
            "APP: Ve a POSICIONES (Difícil). Inténtala hasta que uno no aguante más el calentón.",
            "APP: Ve a la RULETA (Picante). Lo que salga es LEY y no puedes negarte.",
            "APP: Ve a la RULETA (Picante). Lo que salga es LEY y no puedes negarte.", 
            "APP: Ve a la RULETA. Tira 2 veces y combina las dos acciones.",
            "APP: Ve a POSICIONES (Medio). Yo me tumbo y tú haces todo el trabajo.",
            "APP: Tira la RULETA. Si sale tiempo, lo duplicas.",
            "APP: Ve a POSICIONES (Fácil). Hazla, pero con mucha intensidad y rozando solo.",
            
            // --- DESNUDOS Y ELECCIONES ---
            "¡DESNÚDATE COMPLETAMENTE AHORA MISMO!",
            "¡DESNÚDATE COMPLETAMENTE AHORA MISMO!",
            "¡DESNÚDATE COMPLETAMENTE AHORA MISMO!", 
            "ELIGE: O vas a la RULETA (Picante) O te quedas desnudo/a.",
            "ELIGE: O pruebas una POSICIÓN (Difícil) O te dejas atar.",
            "ELIGE: O oral profundo 3 min O te quedas completamente desnudo/a.",
            "ELIGE: O 10 nalgadas fuertes O te quitas toda la ropa.",
            "¡FUERA TODO! Quédate como Dios te trajo al mundo.",

            // --- META-RETOS ---
            "JUEGO: Tus próximos 2 turnos serán OBLIGATORIAMENTE Reto.",
            "JUEGO: Saca un reto ahora mismo y luego tira la ruleta picante.",

            // --- RETOS NORMALES (ENFOCADOS EN CALENTAR Y CONDICIONALES DE RUIDO) ---
            "Hazme sexo oral profundo (mínimo 3 min) pero PARA en cuanto note que me acerco.",
            "Ponte en posición de perrito y deja que te azote 5 veces.",
            "Mastúrbame con la boca llena de agua (o bebida) sin tragar.",
            "Déjame atar tus manos a la cama/silla con lo que tengamos a mano.",
            "Follamos en la posición que YO quiera durante 5 minutos, parando si nos acercamos demasiado.",
            "Lámeme el cuerpo entero, incluidos los pies.",
            "69 durante 3 minutos cronometrados. Prohibido llegar al final.",
            "Introdúcete un dedo (o deja que yo lo haga) y chúpalo después.",
            "Hazme un baile desnudo y tócate.",
            "Ten sexo conmigo sin usar las manos (solo penetración y cadera).",
            "Ponte un vibrador (si hay) o mastúrbate mientras me haces oral.",
            "Introduce solo la puntita durante 2 minutos enteros. Prohibido empujar más.", 
            "Sexo rápido: 2 minutos a máxima velocidad, luego paramos de golpe.",
            "Azótame con un cinturón o cable (suave, luego sube intensidad).",
            "Véndame los ojos y úsame como quieras 5 minutos.",
            "Tócame con los pies en mis partes íntimas.",
            "Grita 'Soy tu puta/o' mientras lo hacemos. (Si hay gente y no puedes: susúrramelo muy guarro al oído y saca OTRA tarjeta de reto extra).",
            "Hazme una paja usando saliva y mirándome.",
            "Quédate quieto/a y deja que te excite sin tocarme (tortura).",
            "Lame mis genitales haciendo el abecedario con la lengua.",
            "Siéntate en mi cara hasta que no pueda respirar.",
            "Sexo de pie (o intentarlo) contra la pared.",
            "Muerde mis pezones fuerte.",
            "Déjame escupirte en la boca o cuerpo (si te gusta).",
            "Introdúcete hielos y luego ten sexo conmigo (sensación frío).",
            "Ponte ropa interior mía y déjatela puesta un rato.",
            "Déjame dominarte por completo los próximos 10 minutos.",
            "Hazme garganta profunda (lo que puedas) 10 veces.",
            "Ten sexo conmigo mirándonos al espejo.",
            "Mastúrbame mirándome a los ojos y para justo cuando empiece a jadear fuerte.", 
            "Mastúrbate hasta el borde del orgasmo y para (Edging).",
            "Déjame grabarte haciendo algo guarro (luego se borra).",
            "Follamos en el suelo (alfombra o duro).",
            "Chupa mis bolas (o clítoris) succionando fuerte.",
            "Tócate y luego pásame los dedos por la boca.",
            "Sexo con la luz del móvil (linterna) iluminando los genitales.",
            "Inmovilízame usando las esposas (o cuerda) y hazme lo que quieras.",
            "Haz ruido, gime muy fuerte, que nos oigan los vecinos. (Si hay gente en casa: prohibido hacer el más mínimo ruido, si se escapa un gemido te quitas una prenda y sacas otro reto).",
            "Susurra guarradas muy sucias mientras me penetras/te penetro."
        ]
    },

    // ============================================================
    // NIVEL 4: EXTREMO (El juego final - Límite sin acabar)
    // ============================================================
    extremo: {
        verdad: [
            "¿Te gustaría ser mi esclavo/a sexual por un día?",
            "¿Cuál es el límite que NO cruzarías nunca?",
            "¿Te gustaría que te castigara físicamente?",
            "¿Has pensado en compartirme con alguien?",
            "¿Te gusta el dolor mezclado con placer?",
            "¿Te excita la idea de ser forzado/a (rol)?",
            "¿Qué objeto de la casa te meterías por la boca?", 
            "¿Te gustaría que te orinara encima (lluvia dorada)?",
            "¿Te pone la asfixia erótica?",
            "¿Te gustaría ser humillado/a sexualmente?",
            "¿Has probado el sexo con dolor?",
            "¿Te gustaría llevar un collar de perro?",
            "¿Qué fetiche raro tienes que no me has contado?",
            "¿Te gustaría tenerme atado y hacerme sufrir de placer?",
            "¿Te pone la idea de exhibirte ante desconocidos?",
            "¿Te gustaría que te tratara como un objeto?",
            "¿Harías un intercambio de parejas?",
            "¿Te gusta que te pegue en la cara (flojo)?",
            "¿Te gustaría usar una mordaza?",
            "¿Te excita llorar o que llore durante el sexo?"
        ],
        reto: [
            // --- APP EXTREMA (FRECUENCIA ALTÍSIMA) ---
            "APP: Ve a POSICIONES (Difícil). Esa postura es OBLIGATORIA hasta que no podáis soportar más las ganas (prohibido acabar).", 
            "APP: Ve a POSICIONES (Difícil). Esa postura es OBLIGATORIA hasta que no podáis soportar más las ganas.", 
            "APP: Tira la RULETA hasta que salga 'Azotar' (o similar intenso) y hazlo x3.",
            "APP: Tira la RULETA hasta que salga algo intenso y hazlo x3.", 
            "APP: Ve a DADOS. Cumple 3 tiradas seguidas sin descanso.",
            "APP: Ve a DADOS. Cumple 3 tiradas seguidas sin descanso.", 
            "APP: Ve a POSICIONES. Busca una imposible y trata de hacerla (Risas o Placer).",
            
            // --- DESNUDOS Y CASTIGOS ---
            "¡DESNUDO INTEGRAL Y PERMANENTE!",
            "¡DESNUDO INTEGRAL Y PERMANENTE!", 
            "ELIGE: O collar de perro y correa O te desnudas.",
            "ELIGE: O aguantas el dolor que yo quiera O te desnudas.",
            "ELIGE: O vas a la RULETA (Picante) O te quedas desnudo/a.",
            "¡FUERA ROPA! Eres mi juguete ahora.",
            
            // --- META-RETOS EXTREMOS ---
            "JUEGO: A partir de este momento, tienes PROHIBIDO elegir Verdad el resto del juego.",
            "JUEGO: Haz tres retos seguidos. Tu voluntad es mía ahora.",

            // --- RETOS EXTREMOS (EDGING Y PROVOCACIÓN) ---
            "Soy tu DUEÑO/A por 15 minutos. Harás todo lo que ordene.",
            "Ponte una mordaza (o prenda en la boca) y déjate follar.",
            "Atadura completa: Usa las esposas para inmovilizarme en la cama. Tú decides qué pasa.",
            "Castigo: 20 azotes fuertes en el culo. Cuéntalos en voz alta.",
            "Sexo con los ojos vendados y manos atadas (Privación sensorial).",
            "Garganta profunda usando un Halls negro en la boca hasta que tengas arcadas 3 veces.",
            "Te prohíbo correrte hasta que yo te dé permiso explícito (ni hoy ni mañana si quiero).",
            "Usa una pinza de la ropa en tus pezones (si aguantas).",
            "Roleplay: Eres una prostituta/o y yo un cliente rudo.",
            "Déjame abofetearte suavemente con mi pene (o pechos) en la cara.",
            "Ponte a 4 patas y ladra como un perro mientras te toco. (Si hay compañeros: imita a un perro sumiso en absoluto silencio, si haces ruido sacas 2 retos de castigo).",
            "Bésame los pies y chupa los dedos uno a uno con devoción.",
            "Ponte hielo en los genitales y aguanta hasta que se derrita.",
            "Hazme un 'Face-sitting' (siéntate en mi cara) hasta que casi me asfixie.",
            "Sexo rudo: Agárrame del pelo y fúerzame (con palabra de seguridad).",
            "Introdúcete el objeto que yo elija (seguro) en la vagina.",
            "Mantén la boca abierta y deja que escupa dentro.",
            "Hazme un masaje rudo, clavando dedos y uñas.",
            "Mastúrbate y cuando estés a punto, PARA. Repite 3 veces. (Edging Extremo)",
            "Déjame escribirte 'PROPIEDAD DE [MI NOMBRE]' en el cuerpo.",
            "Pon tu cabeza entre mis piernas, métete un Halls negro en la boca y hazme oral. Solo puedes parar si te lo suplico (pero no me dejes llegar al final).", 
            "Juego de la asfixia (con cuidado, manos en el cuello).",
            "Te voy a ignorar 5 minutos. Intenta excitarme sin tocar mis genitales.",
            "Tortura de la punta: Penetración solo con la cabeza/punta. No puedes moverte durante 3 minutos.", 
            "Bebe agua de un plato en el suelo como un animal.",
            "Ponte en posición de sumisión y pide permiso para tocarme.",
            "Chupa y estimula mis genitales a fondo usando un Halls negro (el contraste de frío y calor es obligatorio).",
            "Usa cera de vela (baja temperatura/especial) en mi cuerpo.",
            "Muerde fuerte hasta dejar marca (chupetón o dientes).",
            "Sexo oral en la posición '69' de pie (o intentarlo).",
            "No puedes usar las manos para nada durante los próximos 10 min.",
            "Te pongo las esposas con las manos a la espalda y tienes que darme placer solo con la boca.",
            "Insúltame y dime cosas sucias en voz alta mientras lo hacemos. (Si hay gente: dímelas al oído tapándote la boca para que nadie más lo oiga, más otro reto de regalo).",
            "Hazte daño a ti mismo/a (pellizcos, nalgadas) para excitarme.",
            "Ponte de rodillas y ruega por mi polla/coño.",
            "Usa tu ropa interior usada para amordazarme.",
            "Follamos, pero si haces algún ruido, paramos (Silencio total).",
            "Ponte un tapón (o objeto) y mantenlo mientras haces otras cosas.",
            "Déjame tratarte como un muñeco/a (te muevo yo, tú flácido/a).",
            "Hazme sexo oral profundo mientras te azoto el culo.",
            "Inicia el sexo dormido (o simúlalo hasta que despiertes).",
            "Competición de resistencia: Roce constante y agresivo. El primero que suplique acabar recibe un castigo.", 
            "Usa comida (nata, chocolate) en mis genitales y cómelo."
        ]
    }
};
